markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 杨雨日志
host: rainyang.github.io
desc: 关注互联网,持续进步.

custom:
    category:
        tech: 关注技术
        project: 项目&管理
        product: 产品随谈
        think: 非专业思考
        worklog: 工作日志
    categories:
      - name:  tech
        title: 关注技术

      - name:  project
        title: 项目&管理

      - name:  product
        title: 产品随谈

      - name:  think
        title: 非专业思考

      - name:  frontend
        title: 前端技术

      - name:  worklog
        title: 工作日志 

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 杨雨
        email: rainyang2012@qq.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: rainyang                            # GitHub账号
        gravatar: https://avatars1.githubusercontent.com/u/4077434?v=2&s=140  # Gravatar头像标识
        about: 关注移动互联网,专注、极致、快        # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
